---
script: "./script/cibuild"
gemfile: "this/does/not/exist"
env: GITHUB_API_TOKEN=36a1b2a815b98d755528fa6e09b845965fe1e046 # generic user account to get around api rate limit
rvm:
      - "1.8.7"
      - "2.0.0"
before_install:
  - gem update --system 2.1.11 # workaround for https://github.com/rubygems/rubygems/pull/763
